apiVersion: v1
kind: Service
metadata:
  name: {{ include "mantraos-site.fullname" . }}
spec:
  selector:
    app: {{ include "mantraos-site.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: 80
  type: {{ .Values.service.type }}