name: Docs – 80 Column Enforcer

on:
  pull_request:
  push:
    paths:
      - "**/*.md"
      - "scripts/enforce-80.sh"
      - "scripts/wrap-markdown.py"
      - ".github/workflows/line-length.yml"
      - ".editorconfig"
      - "Makefile"

jobs:
  enforce-80:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enforce 80 columns
        run: bash scripts/enforce-80.sh
